/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
static yyconst short int yy_accept[255] =
    {   0,
       37,   37,   40,   38,   39,   38,   38,   23,   24,   30,
       28,   20,   29,   38,   26,   27,   25,   27,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   21,   22,   33,   27,    0,   31,   32,   34,    0,
        0,   37,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    0,    0,    0,    0,   32,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    7,    0,    1,    0,   18,    0,    0,    0,    0,
        0,   35,   37,    0,    0,    0,    0,    3,    0,    5,
        0,    0,   10,   15,    0,    0,    0,    0,    0,    0,

        0,    9,    2,    0,    0,    0,    0,    6,   12,   37,
        0,    0,   36,   11,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    8,    0,    0,   37,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    0,   13,    0,   37,
        0,    0,    0,    0,    0,    0,   17,   19,    0,   37,
        0,    0,   14,    0,   37,    0,    0,    0,   37,    0,
        0,    0,   37,    0,    0,    0,   37,    0,    0,    0,
       37,    0,    0,    0,   37,    0,    0,    0,   37,    0,
        0,    0,   37,    0,    0,    0,   37,    0,    0,    0,
       37,    0,    0,    0,   37,    0,    0,    0,   37,    0,

        0,    0,   37,    0,    0,    0,   37,    0,    0,    0,
       37,    0,    0,    0,   37,    0,    0,    0,   37,    0,
        0,    0,   37,    0,    0,    0,   37,    0,    0,    0,
       37,    0,    0,    0,   37,    0,    0,    0,   37,    0,
        0,    0,   37,    0,    0,    0,   37,    0,    0,    0,
       37,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    5,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,    1,    1,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   20,   19,   19,   19,
        1,    1,    1,   21,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   19,   19,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   19,   42,   19,
       19,   19,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    1,    4,    4,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1
    } ;

static yyconst short int yy_base[317] =
    {   0,
        0,    0,  576,  577,  572,  557,  570,  577,  577,  577,
      569,  577,  577,   42,  577,  554,  553,  552,   43,   27,
       45,   46,   47,   50,   55,   49,   48,   62,   72,   70,
       75,  577,  577,  577,  577,  565,  564,  577,  577,  552,
       88,    0,  562,   87,   64,  541,  525,   92,   95,  100,
      105,  108,  109,  112,  114,  117,  118,  122,    0,  121,
      127,  135,  139,  144,  147,  530,  520,  149,  153,  161,
      154,  166,  169,  168,  170,  171,  173,  175,  176,  183,
      188,  577,    0,  557,  191,  520,  531,  192,  193,  197,
      198,  200,  205,  207,  206,  210,  213,  222,  223,  530,

      553,  227,  228,  229,  231,  236,  243,  244,  245,    0,
      552,  248,  577,  250,  252,  257,  265,  262,  266,  271,
      272,  274,  278,  279,  288,  292,    0,  551,  293,  295,
      296,  300,  297,  305,  310,  312,  314,  319,  320,    0,
      550,  322,  327,  328,  336,  334,  341,  344,  349,    0,
      549,  350,  351,  357,    0,  548,  358,  359,    0,  547,
      363,  366,    0,  546,  371,  372,    0,  545,  373,  376,
        0,  544,  378,  379,    0,  543,  380,  381,    0,  542,
      385,  386,    0,  541,  388,  393,    0,  540,  394,  395,
        0,  539,  398,  400,    0,  538,  401,  402,    0,  537,

      403,  407,    0,  472,  408,  410,    0,  469,  415,  416,
        0,  468,  417,  420,    0,  467,  422,  423,    0,  466,
      424,  425,    0,  464,  429,  430,    0,  461,  432,  437,
        0,  460,  438,  439,    0,  364,  442,  444,    0,  356,
      445,  446,    0,  354,  447,  451,    0,  342,  452,  454,
      577,  337,  459,  577,  473,  475,  334,  477,  317,  479,
      314,  481,  290,  483,  286,  485,  274,  487,  269,  489,
      268,  491,  252,  493,  248,  495,  218,  497,  214,  499,
      155,  501,  151,  503,  147,  505,  139,  507,  133,  509,
      130,  511,  129,  513,  114,  515,  112,  517,   92,  519,

       90,  521,   89,  523,   84,  525,   70,  527,   68,  529,
       66,  531,   64,  533,   62,  535
    } ;

static yyconst short int yy_def[317] =
    {   0,
      254,    1,  254,  254,  254,  254,  255,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  256,  254,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  254,  254,  254,  254,  255,  255,  254,  254,  254,
      254,  257,  254,  256,  254,  254,  254,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  257,  256,
      256,  256,  256,  254,  258,  254,  254,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  254,  259,  254,  258,  254,  254,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  260,  254,

      254,  256,  256,  256,  256,  256,  256,  256,  256,  261,
      254,  260,  254,  256,  256,  256,  256,  256,  256,  262,
      256,  256,  256,  256,  256,  256,  263,  254,  262,  256,
      256,  256,  256,  256,  264,  256,  256,  256,  256,  265,
      254,  264,  256,  256,  256,  266,  256,  256,  256,  267,
      254,  266,  256,  268,  269,  254,  268,  270,  271,  254,
      270,  272,  273,  254,  272,  274,  275,  254,  274,  276,
      277,  254,  276,  278,  279,  254,  278,  280,  281,  254,
      280,  282,  283,  254,  282,  284,  285,  254,  284,  286,
      287,  254,  286,  288,  289,  254,  288,  290,  291,  254,

      290,  292,  293,  254,  292,  294,  295,  254,  294,  296,
      297,  254,  296,  298,  299,  254,  298,  300,  301,  254,
      300,  302,  303,  254,  302,  304,  305,  254,  304,  306,
      307,  254,  306,  308,  309,  254,  308,  310,  311,  254,
      310,  312,  313,  254,  312,  314,  315,  254,  314,  316,
      254,  254,  316,    0,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254
    } ;

static yyconst short int yy_nxt[622] =
    {   0,
        4,    5,    4,    6,    7,    8,    9,   10,   11,   12,
       13,    4,   10,   14,   15,   16,   17,   18,   19,   19,
       20,   19,   19,   21,   22,   19,   23,   24,   25,   19,
       26,   19,   27,   19,   19,   28,   19,   29,   30,   19,
       19,   31,   32,   33,   39,   42,   45,   42,   42,   42,
       42,   42,   42,   40,   46,   41,   43,   42,   43,   43,
       43,   43,   43,   43,   42,  250,   47,  246,   43,  242,
       56,  238,   59,  234,   42,   43,   54,   42,   50,   48,
       49,   51,   55,   43,   52,   43,   53,  230,   43,   42,
       39,   46,  226,  222,   42,  218,   57,   42,   58,   40,

       43,   41,   42,   47,   62,   43,   60,   42,   43,   61,
       42,   42,   63,   43,   42,  214,   42,  210,   43,   42,
       42,   43,   43,   42,   42,   43,   68,   43,   69,   42,
       43,   43,  206,  202,   43,   43,  198,   42,   70,   71,
       43,   42,  194,   73,   77,   72,   82,   75,   43,   83,
      190,   42,   43,   74,  186,   42,   42,   64,  182,   76,
       84,   78,   43,   42,   79,   80,   43,   43,   42,   81,
       42,   42,   42,   42,   43,   42,   91,   42,   42,   43,
       88,   43,   43,   43,   43,   42,   43,   90,   43,   43,
       42,   89,   92,   83,   42,   42,   43,   95,   94,   42,

       42,   43,   42,   93,   84,   43,   43,   42,   42,   42,
       43,   43,   42,   43,   97,   42,   96,  178,   43,   43,
       43,  174,  104,   43,   42,  110,   43,   98,  105,   42,
       42,   42,  102,   42,  107,   43,  111,  103,   42,  108,
       43,   43,   43,  106,   43,   42,   42,   42,  109,   43,
      110,  170,   42,  115,   42,  166,   43,   43,   43,   42,
      114,  111,  117,   43,   42,   43,  119,   42,   42,  116,
       43,  162,  158,  127,   42,   43,   42,  154,   43,   43,
       42,   42,  118,  121,  128,   43,  123,   43,  125,  146,
       42,   43,   43,  135,   42,  127,  122,   42,   42,   42,

      124,   43,   42,  130,  126,   43,  128,   42,   43,   43,
       43,  131,  140,   43,   42,  132,   42,  120,   43,  133,
       99,   42,   42,  141,  140,   43,  136,   43,  138,   42,
       42,  134,   43,   43,  137,  141,  150,   65,   42,  251,
       43,   43,  139,   42,  247,  143,   42,  151,  144,   43,
      145,   42,  150,   42,   43,  147,  243,   43,  239,  155,
      155,  159,   43,  151,   43,  159,  235,  148,  163,  149,
      156,  156,  160,  163,  167,  167,  160,  153,  171,  164,
      171,  175,  175,  179,  164,  168,  168,  179,  183,  172,
      183,  172,  176,  176,  180,  187,  187,  191,  180,  184,

      191,  184,  195,  195,  199,  199,  188,  188,  192,  203,
      203,  192,  207,  196,  196,  200,  200,  207,  211,  211,
      204,  204,  215,  208,  215,  219,  219,  223,  208,  212,
      212,  223,  227,  216,  227,  216,  220,  220,  224,  231,
      231,  235,  224,  228,  235,  228,  239,  239,  243,  243,
      232,  232,  236,  247,  247,  236,  251,  240,  240,  244,
      244,  251,  231,  227,  248,  248,  223,  252,  219,  215,
      211,  207,  252,   36,  203,   36,   36,   44,   44,   85,
       85,  112,  112,  129,  129,  142,  142,  152,  152,  157,
      157,  161,  161,  165,  165,  169,  169,  173,  173,  177,

      177,  181,  181,  185,  185,  189,  189,  193,  193,  197,
      197,  201,  201,  205,  205,  209,  209,  213,  213,  217,
      217,  221,  221,  225,  225,  229,  229,  233,  233,  237,
      237,  241,  241,  245,  245,  249,  249,  253,  253,  199,
      195,  191,  187,  183,  179,  175,  171,  167,  163,  159,
      155,  150,  140,  127,  110,  113,  113,  101,  100,   83,
       87,   86,   67,   66,   42,   64,   37,   37,   35,   35,
       35,   38,   37,   35,   34,  254,    3,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254
    } ;

static yyconst short int yy_chk[622] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   14,   19,   20,   21,   22,   23,
       27,   26,   24,   14,   20,   14,   19,   25,   21,   22,
       23,   27,   26,   24,   28,  315,   20,  313,   25,  311,
       27,  309,   30,  307,   29,   28,   26,   31,   23,   21,
       22,   24,   26,   30,   24,   29,   25,  305,   31,   44,
       41,   45,  303,  301,   48,  299,   28,   49,   29,   41,

       44,   41,   50,   45,   31,   48,   30,   51,   49,   30,
       52,   53,   31,   50,   54,  297,   55,  295,   51,   56,
       57,   52,   53,   60,   58,   54,   48,   55,   49,   61,
       56,   57,  293,  291,   60,   58,  289,   62,   50,   51,
       61,   63,  287,   53,   58,   52,   64,   56,   62,   65,
      285,   68,   63,   55,  283,   69,   71,   64,  281,   57,
       65,   60,   68,   70,   61,   62,   69,   71,   72,   63,
       74,   73,   75,   76,   70,   77,   71,   78,   79,   72,
       68,   74,   73,   75,   76,   80,   77,   70,   78,   79,
       81,   69,   73,   85,   88,   89,   80,   78,   77,   90,

       91,   81,   92,   75,   85,   88,   89,   93,   95,   94,
       90,   91,   96,   92,   80,   97,   79,  279,   93,   95,
       94,  277,   92,   96,   98,   99,   97,   81,   94,  102,
      103,  104,   89,  105,   96,   98,   99,   91,  106,   97,
      102,  103,  104,   95,  105,  107,  108,  109,   98,  106,
      112,  275,  114,  105,  115,  273,  107,  108,  109,  116,
      104,  112,  106,  114,  118,  115,  109,  117,  119,  105,
      116,  271,  269,  120,  121,  118,  122,  267,  117,  119,
      123,  124,  107,  115,  120,  121,  117,  122,  119,  265,
      125,  123,  124,  263,  126,  129,  116,  130,  131,  133,

      118,  125,  132,  121,  119,  126,  129,  134,  130,  131,
      133,  122,  135,  132,  136,  123,  137,  261,  134,  125,
      259,  138,  139,  135,  142,  136,  131,  137,  133,  143,
      144,  126,  138,  139,  132,  142,  146,  257,  145,  252,
      143,  144,  134,  147,  248,  136,  148,  146,  137,  145,
      139,  149,  152,  153,  147,  143,  244,  148,  240,  154,
      157,  158,  149,  152,  153,  161,  236,  144,  162,  145,
      154,  157,  158,  165,  166,  169,  161,  149,  170,  162,
      173,  174,  177,  178,  165,  166,  169,  181,  182,  170,
      185,  173,  174,  177,  178,  186,  189,  190,  181,  182,

      193,  185,  194,  197,  198,  201,  186,  189,  190,  202,
      205,  193,  206,  194,  197,  198,  201,  209,  210,  213,
      202,  205,  214,  206,  217,  218,  221,  222,  209,  210,
      213,  225,  226,  214,  229,  217,  218,  221,  222,  230,
      233,  234,  225,  226,  237,  229,  238,  241,  242,  245,
      230,  233,  234,  246,  249,  237,  250,  238,  241,  242,
      245,  253,  232,  228,  246,  249,  224,  250,  220,  216,
      212,  208,  253,  255,  204,  255,  255,  256,  256,  258,
      258,  260,  260,  262,  262,  264,  264,  266,  266,  268,
      268,  270,  270,  272,  272,  274,  274,  276,  276,  278,

      278,  280,  280,  282,  282,  284,  284,  286,  286,  288,
      288,  290,  290,  292,  292,  294,  294,  296,  296,  298,
      298,  300,  300,  302,  302,  304,  304,  306,  306,  308,
      308,  310,  310,  312,  312,  314,  314,  316,  316,  200,
      196,  192,  188,  184,  180,  176,  172,  168,  164,  160,
      156,  151,  141,  128,  111,  101,  100,   87,   86,   84,
       67,   66,   47,   46,   43,   40,   37,   36,   18,   17,
       16,   11,    7,    6,    5,    3,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 3 "lex.l"

    #include <string.h>
    #include <stdlib.h>
    /*
        Incluir definicoes criadas pelo bison e exportadas para um ficheiro".h"
    */
    #include "sintax.hpp"
    using namespace std;
    // Caracteres invalidos
    void yyerror(char *s);
#line 615 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 25 "lex.l"


#line 780 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 255 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 577 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "lex.l"
{ return INT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "lex.l"
{ return FLOAT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "lex.l"
{return BOOL;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "lex.l"
{ return SE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "lex.l"
{ return SENAO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "lex.l"
{ return ENQUANTO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "lex.l"
{ return PARA; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "lex.l"
{ return ESTRUCT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "lex.l"
{ return CONST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "lex.l"
{ return MAIN;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "lex.l"
{ return GLOBAL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "lex.l"
{ return ESCREVE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "lex.l"
{ return ESCREVETUDO; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "lex.l"
{ return ESCREVESTRING; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "lex.l"
{ return LE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "lex.l"
{ return LETUDO; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "lex.l"
{ return LESTRING; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "lex.l"
{ return EXPOENTE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "lex.l"
{ return RAIZ; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 49 "lex.l"
{ return(VIRGULA); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 50 "lex.l"
{ return(ABRECHAVETA); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 51 "lex.l"
{ return(FECHACHAVETA); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 52 "lex.l"
{ return(ABREPARENT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 53 "lex.l"
{ return(FECHAPARENT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "lex.l"
{ return(IGUAL); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 55 "lex.l"
{ return(PV); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 56 "lex.l"
{ return(OCONDICIONAL); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 57 "lex.l"
{ return(MAIS); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 58 "lex.l"
{ return(MENOS); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 59 "lex.l"
{ return (OPERADOR); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 61 "lex.l"
{ return(COMENTARIO); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 62 "lex.l"
{ return(ESPACO); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 63 "lex.l"
{ return(PARAGRAFO); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 64 "lex.l"
{ return(INTEIRO); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 65 "lex.l"
{ return(REAL); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 66 "lex.l"
{ return(BOOLEANO); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "lex.l"
{strcpy(yylval.nome_var,yytext); return(IDENT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "lex.l"
{ yyerror("caracter nao esperado"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "lex.l"
ECHO;
	YY_BREAK
#line 1058 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 255 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 255 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 254);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 72 "lex.l"

